### ISSUE TITLE
Frozen notebook

### ISSUE THREAD

**Issue by adamwiggins** [inkandswitch/livebook#49]
http://livebook-staging.inkandswitch.com/d/Hi3QXRv1jxBd

Tracebook from dev tools console:

```
ERR abort() at Error
    at jsStackTrace (eval at FunctionPromise (http://livebook-staging.inkandswitch.com/pypyjs/FunctionPromise.js:1:0), <anonymous>:3:20729)
    at stackTrace (eval at FunctionPromise (http://livebook-staging.inkandswitch.com/pypyjs/FunctionPromise.js:1:0), <anonymous>:3:20912)
    at Object.abort (eval at FunctionPromise (http://livebook-staging.inkandswitch.com/pypyjs/FunctionPromise.js:1:0), <anonymous>:88:7170)
    at _abort (eval at FunctionPromise (http://livebook-staging.inkandswitch.com/pypyjs/FunctionPromise.js:1:0), <anonymous>:3:168353)
    at eFd (eval at FunctionPromise (http://livebook-staging.inkandswitch.com/pypyjs/FunctionPromise.js:1:0), <anonymous>:19:208484)
    at Object.Zf [as _pypy_execute_source] (eval at FunctionPromise (http://livebook-staging.inkandswitch.com/pypyjs/FunctionPromise.js:1:0), <anonymous>:7:21152)
    at promise (http://livebook-staging.inkandswitch.com/pypyjs/pypyjs.js:466:22)
    at pypyjs._execute_source (http://livebook-staging.inkandswitch.com/pypyjs/pypyjs.js:457:10)
    at http://livebook-staging.inkandswitch.com/pypyjs/pypyjs.js:536:21
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information. Object
/js/worker.js:158 Unknown ERROR abort() at Error
    at jsStackTrace (eval at FunctionPromise (http://livebook-staging.inkandswitch.com/pypyjs/FunctionPromise.js:1:0), <anonymous>:3:20729)
    at stackTrace (eval at FunctionPromise (http://livebook-staging.inkandswitch.com/pypyjs/FunctionPromise.js:1:0), <anonymous>:3:20912)
    at Object.abort (eval at FunctionPromise (http://livebook-staging.inkandswitch.com/pypyjs/FunctionPromise.js:1:0), <anonymous>:88:7170)
    at _abort (eval at FunctionPromise (http://livebook-staging.inkandswitch.com/pypyjs/FunctionPromise.js:1:0), <anonymous>:3:168353)
    at eFd (eval at FunctionPromise (http://livebook-staging.inkandswitch.com/pypyjs/FunctionPromise.js:1:0), <anonymous>:19:208484)
    at Object.Zf [as _pypy_execute_source] (eval at FunctionPromise (http://livebook-staging.inkandswitch.com/pypyjs/FunctionPromise.js:1:0), <anonymous>:7:21152)
    at promise (http://livebook-staging.inkandswitch.com/pypyjs/pypyjs.js:466:22)
    at pypyjs._execute_source (http://livebook-staging.inkandswitch.com/pypyjs/pypyjs.js:457:10)
    at http://livebook-staging.inkandswitch.com/pypyjs/pypyjs.js:536:21
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

**Comment by orionz** [comment]
Could not reproduce.  I have noticed that sometimes python breaks when an abort() is called internally.  The only way I know reliably to do this is `import numpy`.  Opened a ticket with pypyjs.  Maybe they know a good way to reboot pypy.

**Comment by adamwiggins** [comment]
old / no longer relevant
