### ISSUE TITLE
"data.descri" -> Unknown error, see logs

### ISSUE THREAD

**Issue by adamwiggins** [inkandswitch/livebook#77]
Steps to reproduce:

1. welcome notebook
2. change "data.head()" to "data.descri"

<img width="266" alt="screen shot 2016-02-03 at 22 25 24" src="https://cloud.githubusercontent.com/assets/177/12797592/0af054fc-cac5-11e5-9f2b-7317e89b5135.png">

Dev console output:

```
ERR pypyjsErrormessage: "'descri'"name: "KeyError"stack: (...)trace: "Traceback (most recent call last):↵  File "<string>", line 1, in <module>↵  File "/lib/pypyjs/lib_pypy/livebook.py", line 186, in execute↵    checkpoint(cell,val,local)↵  File "/lib/pypyjs/lib_pypy/livebook.py", line 140, in checkpoint↵    val2 = ["html", val.to_js()]↵  File "/lib/pypyjs/lib_pypy/pandas.py", line 177, in to_js↵    d1 = [self.data[self.column][i] for i in self.idx]↵KeyError: 'descri'↵"__proto__: Error
    at http://livebook-staging.inkandswitch.com/pypyjs/pypyjs.js:959:26
    at http://livebook-staging.inkandswitch.com/pypyjs/pypyjs.js:1017:2
    at Object.0 (http://livebook-staging.inkandswitch.com/js/worker.js:111:7)
    at __webpack_require__ (http://livebook-staging.inkandswitch.com/js/worker.js:20:30)
    at 0 (http://livebook-staging.inkandswitch.com/js/worker.js:40:18)
    at http://livebook-staging.inkandswitch.com/js/worker.js:43:10
```

**Comment by adamwiggins** [comment]
Should mention that expected result is something like "AttributeError: 'DataFrame' object has no attribute 'descri'"
